### ISSUE TITLE
[BUG] Sandwich export not working

### ISSUE THREAD

**Issue by electron271** [SoupDevHub/Sandwich-Machene#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error when generating sandwiches to sandwiches.txt (See logs)

### Expected Behavior

It to generate sandwiches to sandwiches.txt

### Steps To Reproduce

1. Run the program
2. Choose option 2
3. Choose 2 or more (1 works for some reason)
4. Get error

### Environment

```markdown
- OS: Debian 11 Stable
- Python: 3.9.2
- pip3: N/A
```

### Anything else?

```
Sandwich Machine
github.com/SoupDevHub/Sandwich-Machine

Menu
1. Generate a sandwich
2. Generate a sandwich (and output it to a file)
Please enter a option between 1-2 (not higher or lower, that may break our system)
2
How many sandwiches? (Too much may lag the system)
2
Traceback (most recent call last):
  File "/home/electron271/Desktop/projects/Sandwich-Machine/main.py", line 43, in <module>
    thing1 = choice(quality_control.qcthings(sandwichtype))
  File "/home/electron271/Desktop/projects/Sandwich-Machine/quality_control.py", line 10, in qcthings
    return things
UnboundLocalError: local variable 'things' referenced before assignment
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by electron271** [comment]
fixed by 7231563e05c91252b8926929ce1a27e49897a842
